urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "sphynx"

urlpatterns = [
    path('', views.index, name="index"),
    path('category/<int:id>/', views.category, name="category"),
    path('thread/<int:id>/', views.thread, name="thread"),
    path('new/<int:id>/', views.newThread, name="newthread"),
    path('profile/<int:id>/', views.profile, name="profile"),
    path('auth/', views.auth, name="auth"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('comment/<int:id>/', views.comment, name="comment"),
    path('edit/<int:id>/', views.edit, name="edit"),
]

models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse

User = get_user_model()
# Create your models here.

class PostCategory(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name

    def getRecentThreads(self, ammount=20):
        return self.thread_set.all().order_by("-posted")[:ammount]

class PostIcon(models.Model):
    path = models.CharField(max_length=150)
    
    def __str__(self):
        return self.path


class UserDetails(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    custom_title = models.CharField(max_length=30, null=True)
    profile_pic = models.CharField(max_length=30, default="new.png")
    bio = models.CharField(max_length=150, blank=True)
    moderator = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserDetails.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userdetails.save()



class Thread(models.Model):
    title = models.CharField(max_length=25)
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE)
    icon = models.IntegerField()
    body = models.TextField(max_length=500)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE) # TODO: no cascade, just write banned user
    posted = models.DateTimeField(default=timezone.now)
    edited_on = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

    def getRedirect(self):
        return HttpResponseRedirect(reverse('sphynx:thread', kwargs={'id': self.id}))

    def hasPermissionToEdit(self, user):
        if user.is_authenticated == False:
            return False
        if self.author == user:
            return True
        if user.is_staff or user.is_superuser:
            return True
        if user.userdetails.moderator:
            return True
        return False
        


class Comment(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    body = models.TextField(max_length=500) # TODO: max length to settings
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.body


#TODO: add bookmark

templates/forum/auth.html
{% extends './base.html' %}

{% block head %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<style>
  input[type=text] {
    color:white;
  }
  input[type=email] {
    color:white;
  }
  input[type=password] {
    color:white;
  }

</style>
{% endblock %}

{% block content %}
<div class="container">

    
  
        <br><br>
      </div>
    </div>
  
    {% if errormsg %}
    <h2 style="text-align:center;" class="red-text">{{ errormsg }}</h2>
    {% endif %}

    <div class="row container">

      <div class="col s6 grey darken-4">
        <!-- Grey navigation panel -->
        <h4>Login</h4>
        <form method="POST" action="{% url 'sphynx:login' %}">
        {% csrf_token %}
        <input type="text" name="next" hidden value="{{ request.GET.next }}">
        <div class="input-field col s12">
          <input id="username" name="username" type="text" class="validate white-text" required>
          <label for="username" class="no-select-extra">Username</label>
        </div>
        <div class="input-field col s12">
          <input id="lpassword" name="password" type="password" class="validate white-text" required>
          <label for="lpassword">Password</label>
        </div>

        <div class="g-recaptcha" data-sitekey="6LfvHe4UAAAAAEavzqRDfgKvlKpY_SqUU_A0YKa9" data-theme="dark"></div>
        <br>
        <br>
        <button class="btn waves-effect waves-light" type="submit" name="action" style="margin-top:100px">Submit
          <i class="material-icons right">send</i>
        </button>
    </form>
      </div>
  
      <div class="col s6 col s6 grey darken-4">
        <!-- Teal page content  -->
        <h4>Sign Up</h4>
        <form method="POST" >
        {% csrf_token %}
        {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
        
            <div class="g-recaptcha" data-sitekey="6LfvHe4UAAAAAEavzqRDfgKvlKpY_SqUU_A0YKa9" data-theme="dark"></div>

        <button class="btn waves-effect waves-light" type="submit" name="action" style="margin-top:95px;">Submit
          <i class="material-icons right">send</i>
        </button>
        </form>
      </div>
  
    </div>

  </div>
  <br><br><br>
{% endblock %}

templates/forum/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<title>Sphynx Forums</title>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>


  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'forum/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'forum/css/style.css' %} " type="text/css" rel="stylesheet" media="screen,projection"/>
  {% block head %}
  {% endblock %}
</head>
<body>
    
  <div class="container">
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container no-select-extra">
      <a id="logo-container" href="{% url 'sphynx:index' %}" class="brand-logo"><i class="material-icons">polymer</i>
        <p class="brand-text" >Sphynx Forum</p>
      </a>

      <ul class="right hide-on-med-and-down">
        {% if request.user.is_authenticated %}
        <li>Welcome, {{ request.user.username }}</li>
        {% else %}
        <li><a href="{% url 'sphynx:auth' %}">Login Or Register</a></li>
        {% endif %}
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="{% url 'sphynx:auth' %}">Login Or Register</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  </div>
  <div class="row container no-select-extra">
    <div class="col s12 m3">
        
        {% if categories %}

        {% include './misc/categorylist.html' %}
      
        {% endif %}
      <br>

      {% if discord %}
      {% include './misc/discord.html' %}
      {% endif %}
      
    </div>

  {% block content %}
  {% endblock %}
  </div>

 {% if pages %}
  <ul class="pagination container">
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    <li class="active teal"><a href="#!" class="black-text">1</a></li>
    <li class="waves-effect"><a href="#!" class="white-text">2</a></li>
    <li class="waves-effect"><a href="#!" class="white-text">3</a></li>
    <li class="waves-effect"><a href="#!" class="white-text">4</a></li>
    <li class="waves-effect"><a href="#!" class="white-text">5</a></li>
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
  </ul>
  <br>
{% endif %}


<div class="fixed-action-btn no-select-extra">
  <a class="btn-floating btn-large red waves-effect waves-light red">
    <i class="large material-icons">person</i>
  </a>
  <ul>
    <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
    <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
    <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
    <li><a class="btn-floating blue"><i class="material-icons">settings</i></a></li>
  </ul>
</div>

  <footer class="page-footer grey darken-4">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, commodi reprehenderit dolorum similique omnis voluptatibus quam est dolore hic eius odio ullam voluptatum dicta consequatur fuga vel molestiae, earum illum!</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Design made by <a class="red-text" href="https://barz.cc">Barz</a>
      <br>
      Powered by <a class="red-text" href="https://sphynx.pw">Sphynx</a>
      </div>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'forum/js/materialize.js' %}"></script>
  <script src="{% static 'forum/js/init.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

  <script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
      direction: 'left',
      hoverEnabled: false
    });
  });
  </script>
  <script>
      window.onload = function() {
    var recaptcha = document.querySelector('#g-recaptcha-response');

    if(recaptcha) {
            recaptcha.setAttribute("required", "required");
    }
    var recaptcha = document.querySelector('#g-recaptcha-response-1');

    if(recaptcha) {
            recaptcha.setAttribute("required", "required");
    }
    jQuery(function($){
        $('.g-recaptcha').attr('data-theme', 'dark');
        });
    
};
  </script>
</body>

templates/forum/basic.html
{% extends './base.html' %}
{% load static %}
{% block content %}



      <div class="col s12 m9">
       
        <ul class="collection">
          <li class="collection-item grey darken-4"><h4>{% if current_category %} {{ current_category }} {% else %} Recent Posts {% endif %}</h4></li>
          {% if current_category and request.user.is_authenticated %}
          <li class="collection-item grey darken-4">
            <a href="{% url 'sphynx:newthread' current_category.id %}" class="link" style="text-align:right;display:block;"><p style="margin:0;font-size:15px;display:inline;vertical-align:top;">New Thread</p><i class="material-icons" style="font-size: 22px;">add</i></a>
          </li>
          {% endif %}
          {% if threads %}
          
          {% for thread in threads %}
          <li class="collection-item avatar grey darken-4">
            <img src="{% static 'forum/pfp/'|add:thread.author.userdetails.profile_pic %}" alt="" class="circle">
            <a href="{% url 'sphynx:thread' thread.id %}"><span class="title teal-text bold">{{ thread.title }}</span></a>
            <p class="secondary-content grey darken-4" style="display:inline;text-align:right;margin-right:30px;">{{ thread.posted|timesince }} ago...</p>
            <div class="blockdis">
            <a href="{% url 'sphynx:profile' thread.author.id %}" class="link"><p class="inlinedis">{{ thread.author.username }}</p></a>
            </div>
            <p class="grey-text">{{ thread.body|truncatechars:80 }} </p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>
          {% endfor %}
          
          {% else %}
          {% if current_category %}
          <li class="collection-item grey darken-4"><p>No threads were found... Click <a href="{% url 'sphynx:newthread' current_category.id %}">here</a> to make one!</a></p></li>
          {% else %}
          <li class="collection-item grey darken-4"><p>No threads were found... Click</p></li>
          {% endif %}

          {% endif %}

          <!--<li class="collection-item avatar grey darken-4">
            <i class="material-icons circle">folder</i>
            <span class="title teal-text bold">Witcher 3</span>
            <p>First Line</p>
            <p class="grey-text">Second Line</p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar grey darken-4">
            <i class="material-icons circle green">insert_chart</i>
            <span class="title teal-text bold">Barz's house of fun</span>
            <p>First Line</p>
            <p class="grey-text">Second Line</p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar grey darken-4">
            <i class="material-icons circle red">play_arrow</i>
            <span class="title teal-text bold">Blackwake</span>
            <p>First Line</p>
            <p class="grey-text">Second Line</p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar grey darken-4">
            <img src="https://materializecss.com/images/yuna.jpg" alt="" class="circle">
            <span class="title teal-text bold">GTA 5</span>
            <p>First Line</p>
            <p class="grey-text">Second Line</p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar grey darken-4">
            <i class="material-icons circle">folder</i>
            <span class="title teal-text bold">Witcher 3</span>
            <p>First Line</p>
            <p class="grey-text">Second Line</p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar grey darken-4">
            <i class="material-icons circle green">insert_chart</i>
            <span class="title teal-text bold">Barz's house of fun</span>
            <p>First Line</p>
            <p class="grey-text">Second Line</p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar grey darken-4">
            <i class="material-icons circle red">play_arrow</i>
            <span class="title teal-text bold">Blackwake</span>
            <p>First Line</p>
            <p class="grey-text">Second Line</p>
            <a href="#!" class="secondary-content grey darken-4"><i class="material-icons">grade</i></a>
          </li>-->
        </ul>
      </div>

    </div>








{% endblock content %}

templates/forum/newthread.html
{% extends './base.html' %}
{% load static %}
{% block head %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block content %}
<div class="container">

    

      </div>
    </div>


        <div class="row container">
            <nav>
                <div class="nav-wrapper grey darken-4 forcenoshadow">
                  <div class="col s12">
                    <a href="{% url 'sphynx:index'%}" class="breadcrumb">Home</a>
                    <a href="{% url 'sphynx:category' category.id %}" class="breadcrumb">{{ category }}</a>
                  </div>
                </div>
              </nav>
          <div class="col s2">
            <div class="row">
                <div class="col">
                  <div class="card blue-grey darken-1">
                    <div class="card-content white-text align-center-extra">
                        {% if thread %}
                        <img src="{% static 'forum/pfp/'|add:thread.author.userdetails.profile_pic %}" alt="" class="circle z-depth-3" width="140px">
                        {% else %}
                        <img src="{% static 'forum/pfp/'|add:request.user.userdetails.profile_pic %}" alt="" class="circle z-depth-3" width="140px">
                        {% endif %}
                      <span class="card-title">{% if thread %} {{ thread.author.username }} {% else %} {{ request.user.username }} {% endif %}</span>
                      <p class="red-text accent-1 bold">
                        {% if thread %}
                        {% if thread.author.userdetails.custom_title %} {{ thread.author.userdetails.custom_title }} {% endif %}
                        {% else %} 
                        {% if request.user.userdetails.custom_title %} {{ request.user.userdetails.custom_title }} {% endif %}
                      {% endif %}
                      </p>
                      <p>{% if thread %} {{ thread.author.userdetails.bio }} {% else %} {{ request.user.userdetails.bio }} {% endif %}</p>
                    </div>
                    <div class="card-action align-right-extra">
                      {% if thread %}
                      <a href="{% url 'sphynx:profile' thread.author.id %}">Visit Profile</a>
                      {% else %}
                      <a href="{% url 'sphynx:profile' request.user.id %}">Visit Profile</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
                        
          
          </div>
    
          <div class="col s10">
           
            <ul class="collection">
              <br>
              <form method="POST">
                {% csrf_token %}
              <div class="input-field col s12">
                <textarea id="title" name="title" class="materialize-textarea white-text" minlength="5" maxlength="25" rows="5">{% if thread %} {{ thread.title }} {% endif %}</textarea>
                <label for="title">Title</label>
              </div>
                <div class="input-field col s12">
                  <textarea id="textarea1" name="body" class="materialize-textarea white-text" minlength="15" maxlength="500" rows="5" style="height:15%;">{% if thread %} {{ thread.body }} {% endif %}</textarea>
                  <label for="textarea1">Body</label>
                </div>
                <div class="g-recaptcha" data-sitekey="6LfvHe4UAAAAAEavzqRDfgKvlKpY_SqUU_A0YKa9" data-theme="dark"></div>
                <br>
                <button class="btn waves-effect waves-light" type="submit" name="action" style="margin-bottom:20px;margin-top:90px">Submit
                  <i class="material-icons right">send</i>
                </button>
              </form>
            </ul>
            <br>
          </div>
    
        </div>

  

    
  </div>
  

{% endblock %}

templates/forum/profile.html
{% extends './base.html' %}
{% load static %}


{% block content %}
  
        <br><br>
      </div>
    </div>
      <div class="row container">
          <nav>
              <div class="nav-wrapper grey darken-4 forcenoshadow">
                <div class="col s12">
                  <a href="#!" class="breadcrumb">Users</a>
                  <a href="#!" class="breadcrumb">{{ user.username }}</a>
                </div>
              </div>
            </nav>
        <div class="col s12">
          <div class="row">
              <div class="col s12">
                <div class="card blue-grey darken-1">
                  <div class="card-content white-text align-center-extra">
                      <img src="{% static 'forum/pfp/'|add:user.userdetails.profile_pic %}" alt="" class="circle z-depth-3" width="140px">
                    <span class="card-title">{{ user.username }}</span>
                    <p>{{ user.userdetails.bio }}</p>
                    <p>Registered: <b class="teal-text">{{ user.date_joined|timesince }} ago</b></p>
                    <p>Threads started: {{ user.thread_set.all|length }}</p>
                  </div>
                </div>
              </div>
            </div>
                      
        
        </div>
      </div>
      <h4 class="align-center-extra">Recent posts</h4>
      <div class="row container">
    
          <div class="col s12">
           
            <ul class="collection">
              <li class="collection-item grey darken-4 wrapit">
                  <blockquote>
                    {% for thread in user.thread_set.all %}
                    <nav class="threadlist">
                        <div class="nav-wrapper grey darken-4 forcenoshadow">
                          <div class="col s12">
				  <a href="{% url 'sphynx:category' thread.category.id %}" class="breadcrumb">{{ thread.category.name }}</a>
                            <a href="{% url 'sphynx:thread' thread.id %}" class="breadcrumb">{{ thread.title }}</a>
                          </div>
                        </div>
                      </nav>
                    {% endfor %}
                    </blockquote>
                  </li>
            </ul>
          </div>
    
        </div>
  
        
        </div>
      <br>
  
  

    
  </div>
  

{% endblock %}

templates/forum/thread.html
{% extends './base.html' %}
{% load static %}
{% block head %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block content %}
<div class="container">

    

      </div>
    </div>
      <div class="row container">
          <nav>
              <div class="nav-wrapper grey darken-4 forcenoshadow">
                <div class="col s12">
                  <a href="{% url 'sphynx:category' thread.category.id %}" class="breadcrumb">{{ thread.category }}</a>
                  <a href="#!" class="breadcrumb">{{ thread.title }}</a>
                </div>
              </div>
            </nav>
        <div class="col s2">
          <div class="row">
              <div class="col">
                <div class="card blue-grey darken-1">
                  <div class="card-content white-text align-center-extra">
                      <img src="{% static 'forum/pfp/'|add:thread.author.userdetails.profile_pic %}" alt="" class="circle z-depth-3" width="140px">
                    <span class="card-title">{{ thread.author.username }}</span>
                    <p class="red-text accent-1 bold">{% if thread.author.userdetails.custom_title %} {{ thread.author.userdetails.custom_title }} {% endif %}</p>
                    <p>{{ thread.author.userdetails.bio }}</p>
                  </div>
                  <div class="card-action align-right-extra">
                    <a href="{% url 'sphynx:profile' thread.author.id %}">Visit Profile</a>
                  </div>
                </div>
              </div>
            </div>
                      
        
        </div>
  
        <div class="col s10">
         
          <ul class="collection" id="comment">
            <li class="collection-item grey darken-4"><h4>{{ thread.title }}</h4></li>
            <li class="collection-item grey darken-4 wrapit"><p class="threadbody">{{ thread.body }}</p></li>
          </ul>
          {% if thread.edited_on %}
          <p class="editedstr">Edited {{ thread.edited_on|timesince }} ago...</p>
          {% endif %}
          {% if permissionToEdit == True %}
          <div style="display:block;float:right;">
            <a href="{% url 'sphynx:edit' thread.id %}" class="link" style="text-align:right;display:inline;"><p style="margin:0;font-size:15px;display:inline;vertical-align:top;">Edit</p><i class="material-icons" style="font-size: 18px;vertical-align:sub;">settings</i></a>
          </div>
          {% endif %}
        </div>
  
      </div>
      {% for comment in thread.comment_set.all %}
      <div class="row container">
  
        <div class="col s2">
            <div class="row">
                <div class="col">
                  <div class="card blue-grey darken-1">
                    <div class="card-content white-text align-center-extra">
                        <img src="{% static 'forum/pfp/'|add:comment.author.userdetails.profile_pic %}" alt="" class="circle z-depth-3" width="140px">
                      <span class="card-title">{{ comment.author.username }}</span>
                      <p class="red-text accent-1 bold">{% if comment.author.userdetails.custom_title %} {{ comment.author.userdetails.custom_title }} {% endif %}</p>
                      <p>{{ comment.author.userdetails.bio }}</p>

                    </div>
                    <div class="card-action align-right-extra">
                      <a href="{% url 'sphynx:profile' comment.author.id %}">Visit Profile</a>
                    </div>
                  </div>
                </div>
              </div>
                      
        
        </div>
  
        <div class="col s10">
         
          <ul class="collection">
            <li class="collection-item grey darken-4 wrapit"><p class="threadbody">{{ comment.body }}</p></li>
          </ul>
        </div>
  
      </div>
      {% endfor %}
      
      {% if request.user.is_authenticated %}
        <div class="row container">
  
          <div class="col s2">
            <div class="row">
                <div class="col">
                  <div class="card blue-grey darken-1">
                    <div class="card-content white-text align-center-extra">
                        <img src="{% static 'forum/pfp/'|add:request.user.userdetails.profile_pic %}" alt="" class="circle z-depth-3" width="140px">
                      <span class="card-title">{{ request.user.username }}</span>
                      <p class="red-text accent-1 bold">{% if request.user.userdetails.custom_title %} {{ request.user.userdetails.custom_title }} {% endif %}</p>
                      <p>{{ request.user.userdetails.bio }}</p>
                    </div>
                    <div class="card-action align-right-extra">
                      <a href="{% url 'sphynx:profile' request.user.id %}">Visit Profile</a>
                    </div>
                  </div>
                </div>
              </div>
                        
          
          </div>
    
          <div class="col s10">
           
            <ul class="collection">
              <br>
              <form method="POST" action="{{ commentsite }}">
              {% csrf_token %}
              <div class="input-field col s12">
                  <textarea id="textarea1" name="commentbody" minlength="15" maxlength="500" class="materialize-textarea white-text" rows="5"></textarea>
                  <label for="textarea1">Textarea</label>
                </div>
                <div class="g-recaptcha" data-sitekey="6LfvHe4UAAAAAEavzqRDfgKvlKpY_SqUU_A0YKa9" data-theme="dark"></div>
                <br>
                <button class="btn waves-effect waves-light" type="submit" name="action" style="margin-bottom:20px;margin-top:85px">Submit
                  <i class="material-icons right">send</i>
                </button>
              </form>
            </ul>
            <br>
          </div>
    
        </div>
        {% endif %}

  

    
  </div>
  

{% endblock %}